import type { EEGClinicalCase } from '~/core/cases';

export const eegCases: EEGClinicalCase[] = [
  {
    id: 'absence-hyperventilation',
    title: 'Staring spells provoked by hyperventilation',
    oneLiner:
      'A 9-year-old with brief staring episodes at school is asked to hyperventilate during a routine EEG.',
    chiefComplaint:
      'The teacher reports 10–15 second episodes of unresponsiveness several times a day, with immediate return to baseline afterward.',
    history:
      'No convulsive activity. Normal development. Episodes started 6 months ago and are more frequent during morning classes.',
    syndromeFrame:
      'This is a primary generalized epilepsy problem. The strongest localizing question is whether the discharges arise from thalamocortical circuits bilaterally and synchronously, not from a focal cortical lesion.',
    examFindings: [
      'Normal neurological examination',
      'Episode provoked within 60 seconds of hyperventilation',
      'Abrupt onset and offset of unresponsiveness',
      'No post-ictal confusion',
    ],
    prompt:
      'What EEG pattern do you expect, and why does the abrupt onset-offset argue against focal epilepsy?',
    hints: [
      'Generalized onset should produce bilateral synchronous discharges from the first spike.',
      'Focal seizures typically have a build-up; absence discharges switch on and off.',
    ],
    localizationCues: [
      'Bilateral synchronous 3 Hz spike-and-wave from the first complex.',
      'No lateralized lead-in or focal slowing preceding the discharge.',
    ],
    differentialTraps: [
      'Do not confuse frontal lobe seizures with staring episodes — frontal seizures are typically longer and have motor features or postictal confusion.',
      'Do not call hyperventilation-induced slowing in children pathological — physiological slowing is symmetric and rhythmic.',
    ],
    nextDataRequests: [
      'Full EEG with hyperventilation and photic stimulation',
      'Clinical correlation of EEG events with behavioral arrest',
    ],
    teachingPoints: [
      'Absence epilepsy is the prototype of a network epilepsy generated by thalamocortical circuits.',
      'The EEG is both diagnostic and localizing: bilateral, synchronous, 3 Hz spike-and-wave from a normal background.',
      'If the frequency is slower (<2.5 Hz) or the background is abnormal, reconsider the syndrome classification.',
    ],
    followUpModules: ['brain-atlas', 'neuron', 'ask'],
    expectedPresetId: 'generalized-spike-wave',
    startingPresetId: 'normal-awake',
  },
  {
    id: 'temporal-lobe-epilepsy',
    title: 'Recurrent déjà vu and epigastric aura',
    oneLiner:
      'A 34-year-old presents with a rising epigastric sensation followed by an altered awareness episode witnessed by a colleague.',
    chiefComplaint:
      'Frequent brief episodes of déjà vu with a rising abdominal feeling, sometimes progressing to 60–90 seconds of staring and oral automatisms.',
    history:
      'Febrile seizures in childhood. MRI shows left mesial temporal sclerosis. On levetiracetam but continues to have events.',
    syndromeFrame:
      'This is a mesial temporal lobe epilepsy problem. The aura localizes to limbic cortex; the question is whether interictal EEG shows concordant left temporal discharges.',
    examFindings: [
      'Normal interictal neurological examination',
      'Left mesial temporal sclerosis on MRI',
      'Episodes begin with epigastric aura — mesial temporal signature',
    ],
    prompt:
      'What interictal EEG findings would support the MRI localization, and what would make you doubt it?',
    hints: [
      'Anterior temporal spikes (F7/T3) are most common in mesial temporal epilepsy.',
      'Bilateral independent temporal spikes do not exclude surgical candidacy but change the prognostic calculus.',
    ],
    localizationCues: [
      'Left anterior temporal sharp waves with appropriate field (F7 > T3 > Fp1).',
      'Normal background over the right hemisphere.',
    ],
    differentialTraps: [
      'Do not assume all temporal spikes mean mesial temporal sclerosis — neocortical temporal epilepsy has different semiology.',
      'A normal interictal EEG does not exclude temporal lobe epilepsy.',
    ],
    nextDataRequests: [
      'Video-EEG monitoring to capture a habitual event',
      'Ictal EEG onset lateralization',
    ],
    teachingPoints: [
      'The sensitivity of a single routine EEG for interictal epileptiform discharges in temporal lobe epilepsy is roughly 50%.',
      'Sleep and sleep deprivation increase the yield of temporal spikes.',
      'Concordance between semiology, MRI, and interictal EEG strengthens the surgical hypothesis.',
    ],
    followUpModules: ['brain-atlas', 'ask'],
    expectedPresetId: 'left-temporal-spikes',
    startingPresetId: 'normal-awake',
  },
  {
    id: 'hepatic-encephalopathy',
    title: 'Confusion after a GI bleed in cirrhosis',
    oneLiner:
      'A 62-year-old with known cirrhosis becomes progressively confused 48 hours after an upper GI bleed.',
    chiefComplaint:
      'The neurology team is consulted because the patient is somnolent but arousable, with asterixis and disoriented speech.',
    history:
      'Liver cirrhosis (Child-Pugh C), no prior seizures. Ammonia is elevated. The team wants to know if this is nonconvulsive status epilepticus or metabolic encephalopathy.',
    syndromeFrame:
      'This is a diffuse encephalopathy problem. The key EEG question is whether the slowing is diffuse and reactive (metabolic) versus showing electrographic seizures (NCSE).',
    examFindings: [
      'Somnolent but arousable with stimulation',
      'Bilateral asterixis',
      'No focal neurological deficits',
      'Elevated serum ammonia',
    ],
    prompt:
      'What EEG pattern distinguishes metabolic encephalopathy from nonconvulsive status, and how does reactivity factor in?',
    hints: [
      'Metabolic encephalopathy produces diffuse slowing that typically reacts to stimulation.',
      'NCSE should show evolving electrographic seizure patterns — evolution in frequency, morphology, or distribution.',
    ],
    localizationCues: [
      'Diffuse theta-delta slowing without focal features.',
      'Background reactivity to stimulation favors encephalopathy over NCSE.',
    ],
    differentialTraps: [
      'Triphasic waves can be seen in metabolic encephalopathy and can mimic generalized periodic discharges — clinical context resolves the ambiguity.',
      'Do not empirically treat with IV benzodiazepines as a diagnostic test without considering the clinical picture first.',
    ],
    nextDataRequests: [
      'EEG with stimulation protocol to test reactivity',
      'Trend ammonia and mental status with treatment',
    ],
    teachingPoints: [
      'The grade of diffuse slowing roughly parallels the severity of encephalopathy: theta in mild, delta in severe, burst suppression in profound.',
      'Reactivity is one of the most clinically useful EEG features in the ICU — unreactive backgrounds carry a worse prognosis.',
      'Triphasic waves are not specific to hepatic encephalopathy; they occur in renal failure, medication toxicity, and other metabolic states.',
    ],
    followUpModules: ['brain-atlas', 'ecg', 'ask'],
    expectedPresetId: 'encephalopathy',
    startingPresetId: 'normal-awake',
  },
  {
    id: 'anoxic-brain-injury',
    title: 'Post-cardiac-arrest neuroprognostication',
    oneLiner:
      'A 55-year-old is comatose 72 hours after out-of-hospital cardiac arrest with ROSC after 18 minutes.',
    chiefComplaint:
      'The ICU team requests EEG as part of multimodal neuroprognostication. The patient is off sedation for 24 hours and remains comatose.',
    history:
      'Witnessed ventricular fibrillation arrest. Targeted temperature management completed. No clinical improvement after rewarming. Brainstem reflexes present but no motor response above stereotyped extensor posturing.',
    syndromeFrame:
      'This is a neuroprognostication problem after hypoxic-ischemic encephalopathy. The EEG pattern and its reactivity contribute to multimodal outcome prediction but must not be interpreted in isolation.',
    examFindings: [
      'Comatose, no eye opening',
      'Extensor posturing to pain',
      'Brainstem reflexes present',
      'Off sedation for 24 hours',
    ],
    prompt:
      'What EEG pattern would be most ominous, and why should it not be the sole basis for withdrawal of care?',
    hints: [
      'Burst suppression and electrocerebral silence are poor prognostic signs, but must be interpreted in the context of timing, temperature, and sedation.',
      'A continuous and reactive background after rewarming is a favorable sign.',
    ],
    localizationCues: [
      'The pattern of interest is diffuse — this is a global cortical injury.',
      'Reactivity testing (stimulation during EEG) adds critical information beyond the resting pattern.',
    ],
    differentialTraps: [
      'Sedation and hypothermia can mimic severe EEG patterns — always confirm adequate drug clearance.',
      'Myoclonic status epilepticus can look devastating but occasional patients with early myoclonus still recover with a continuous reactive EEG background.',
    ],
    nextDataRequests: [
      'Continuous EEG monitoring for evolution of background',
      'Somatosensory evoked potentials (bilateral N20)',
      'Serum NSE at 48 and 72 hours',
    ],
    teachingPoints: [
      'EEG is one component of multimodal neuroprognostication — no single test should determine outcome alone.',
      'The most ominous EEG patterns post-arrest are: unreactive burst suppression, suppression with superimposed periodic discharges, and electrocerebral silence.',
      'A continuous and reactive background by 72 hours post-arrest is among the most reliable favorable predictors.',
    ],
    followUpModules: ['ecg', 'brain-atlas', 'ask'],
    expectedPresetId: 'burst-suppression',
    startingPresetId: 'encephalopathy',
  },
  {
    id: 'focal-slowing-stroke',
    title: 'New left hemiparesis with EEG for seizure concern',
    oneLiner:
      'A 71-year-old with acute right MCA infarct has a witnessed rhythmic eye deviation and the team wants to rule out seizures.',
    chiefComplaint:
      'Acute right MCA territory stroke with new left hemiparesis. A brief episode of rightward eye deviation was observed and the team is concerned about seizures.',
    history:
      'CT angiography confirmed right MCA occlusion, now post-thrombectomy with partial reperfusion. The episodic eye deviation resolved spontaneously after 2 minutes.',
    syndromeFrame:
      'This is a post-stroke EEG interpretation problem. The key distinction is focal slowing from the structural lesion (expected and non-epileptic) versus superimposed electrographic seizures.',
    examFindings: [
      'Left hemiparesis and left neglect',
      'Right MCA territory infarct on imaging',
      'Single episode of transient rightward eye deviation',
    ],
    prompt:
      'How would you distinguish expected post-stroke focal slowing from electrographic seizures on this EEG?',
    hints: [
      'Focal slowing from a structural lesion is persistent, non-evolving, and polymorphic.',
      'Seizures show evolution: a change in frequency, amplitude, morphology, or spatial distribution over seconds.',
    ],
    localizationCues: [
      'Right hemisphere focal delta-theta slowing concordant with the MCA territory.',
      'Look for evolution to distinguish seizure from slowing.',
    ],
    differentialTraps: [
      'Rhythmic delta activity (RDA) is a pattern that sits on the ictal-interictal continuum — it is not the same as clearly evolving seizures.',
      'Lateralized periodic discharges (LPDs) in acute stroke can occur without necessarily being seizures.',
    ],
    nextDataRequests: [
      'Continuous EEG monitoring for 24–48 hours',
      'Clinical correlation of any EEG changes with bedside events',
    ],
    teachingPoints: [
      'Post-stroke EEGs almost always show focal slowing over the lesion territory — this is structural, not epileptic.',
      'The critical EEG skill is recognizing evolution: unequivocal seizures change in frequency and field over time.',
      'Lateralized periodic discharges and lateralized rhythmic delta activity sit on the ictal-interictal continuum and require clinical context for interpretation.',
    ],
    followUpModules: ['brain-atlas', 'ask'],
    expectedPresetId: 'focal-temporal-slowing',
    startingPresetId: 'normal-awake',
  },
];
